// firebase_options.dart file in services folder

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTrjzHbnGqWmJSITnWaJMSbM-y2t1tJU',
    appId: '1:16822394471:web:b5f21a7d94fb5d1e717ec2',
    messagingSenderId: '16822394471',
    projectId: 'employee-discount-4f875',
    authDomain: 'employee-discount-4f875.firebaseapp.com',
    storageBucket: 'employee-discount-4f875.firebasestorage.app',
    measurementId: 'G-TE8E5R0WJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCALPHY9xJdz3-VhqrSzWYbahsPXY3xkBc',
    appId: '1:16822394471:android:07696aaf73076acd717ec2',
    messagingSenderId: '16822394471',
    projectId: 'employee-discount-4f875',
    storageBucket: 'employee-discount-4f875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0zi-cU97vgkjH1z9qyTqNxMP9sBzBGw',
    appId: '1:16822394471:ios:f89b8fdb9bbefc3f717ec2',
    messagingSenderId: '16822394471',
    projectId: 'employee-discount-4f875',
    storageBucket: 'employee-discount-4f875.firebasestorage.app',
    iosBundleId: 'com.example.discountPortalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0zi-cU97vgkjH1z9qyTqNxMP9sBzBGw',
    appId: '1:16822394471:ios:f89b8fdb9bbefc3f717ec2',
    messagingSenderId: '16822394471',
    projectId: 'employee-discount-4f875',
    storageBucket: 'employee-discount-4f875.firebasestorage.app',
    iosBundleId: 'com.example.discountPortalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTrjzHbnGqWmJSITnWaJMSbM-y2t1tJU',
    appId: '1:16822394471:web:2c196810700c0e7e717ec2',
    messagingSenderId: '16822394471',
    projectId: 'employee-discount-4f875',
    authDomain: 'employee-discount-4f875.firebaseapp.com',
    storageBucket: 'employee-discount-4f875.firebasestorage.app',
    measurementId: 'G-QP3MTCQDNS',
  );
}
